# Generated by Django 3.2.13 on 2022-07-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('Formid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Formdata', models.JSONField()),
            ],
        ),
    ]
