# Generated by Django 3.2.13 on 2022-07-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formcreater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='forms',
            name='Formid',
            field=models.BigAutoField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Qid', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('required', models.BooleanField()),
                ('typeofquestion', models.CharField(max_length=200)),
                ('formid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formcreater.forms')),
            ],
        ),
    ]
