# Generated by Django 3.2.13 on 2022-07-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formcreater', '0002_auto_20220712_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
