# Generated by Django 3.2.13 on 2022-07-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formcreater', '0003_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterField(
            model_name='forms',
            name='Formid',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
