# Generated by Django 3.2.13 on 2022-07-12 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formcreater', '0004_auto_20220712_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='Formdata',
        ),
        migrations.AddField(
            model_name='forms',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='forms',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Qid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('Type', models.CharField(choices=[('Short answer', 'Short answer'), ('Paragraph', 'Paragraph'), ('Multiple Choice', 'Multiple Choice'), ('Checkbox', 'Checkbox'), ('Drop-down', 'Drop-down'), ('Linear scale', 'Linear scale'), ('Tick box grid', 'Tick box grid'), ('Mutiple-choice grid', 'Mutiple-choice grid'), ('Date', 'Date'), ('time', 'time')], max_length=20)),
                ('formid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formcreater.forms')),
            ],
        ),
        migrations.CreateModel(
            name='grids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.JSONField()),
                ('column', models.JSONField()),
                ('Qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formcreater.question')),
            ],
        ),
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.JSONField()),
                ('Qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formcreater.question')),
            ],
        ),
    ]
