# Generated by Django 3.2.13 on 2022-07-12 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formcreater', '0005_auto_20220712_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField()),
                ('formid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formcreater.forms')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formcreater.question')),
            ],
        ),
    ]
