# Generated by Django 3.2.13 on 2022-07-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formcreater', '0007_question_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.CharField(choices=[('required', 'True'), (' ', 'False')], max_length=20),
        ),
    ]
