# Generated by Django 3.2.13 on 2022-07-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formcreater', '0008_alter_question_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='id',
        ),
        migrations.AddField(
            model_name='responses',
            name='responseid',
            field=models.CharField(default=1, max_length=8, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
