# Generated by Django 3.2.13 on 2022-07-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formcreater', '0010_auto_20220713_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Qid',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='formresponses',
            old_name='qid',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='Formid',
            new_name='form_id',
        ),
        migrations.RenameField(
            model_name='grids',
            old_name='Qid',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='formid',
            new_name='form_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Type',
            new_name='question_Type',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Qid',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='formid',
            new_name='form_id',
        ),
    ]
