# Generated by Django 3.2.13 on 2022-07-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formcreater', '0011_auto_20220715_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formresponses',
            old_name='responseid',
            new_name='response_id',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='responseid',
            new_name='response_id',
        ),
    ]
