# Generated by Django 3.2.13 on 2022-07-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formcreater', '0012_auto_20220715_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='questionid',
        ),
        migrations.RenameField(
            model_name='formresponses',
            old_name='question_id',
            new_name='questionid',
        ),
        migrations.RenameField(
            model_name='formresponses',
            old_name='response_id',
            new_name='responseid',
        ),
        migrations.RenameField(
            model_name='grids',
            old_name='question_id',
            new_name='questionid',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='form_id',
            new_name='formid',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_Type',
            new_name='questionType',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_id',
            new_name='questionid',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='form_id',
            new_name='formid',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='response_id',
            new_name='responseid',
        ),
    ]
