# Generated by Django 3.2.13 on 2022-07-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formcreater', '0013_auto_20220715_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='questionid',
            new_name='Qid',
        ),
        migrations.RenameField(
            model_name='formresponses',
            old_name='questionid',
            new_name='qid',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='form_id',
            new_name='Formid',
        ),
        migrations.RenameField(
            model_name='grids',
            old_name='questionid',
            new_name='Qid',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionid',
            new_name='Qid',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionType',
            new_name='Type',
        ),
    ]
