# Generated by Django 3.2.13 on 2022-07-15 07:57

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('formcreater', '0014_auto_20220715_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Qid',
            new_name='questionid',
        ),
        migrations.RenameField(
            model_name='formresponses',
            old_name='qid',
            new_name='questionid',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='Formid',
            new_name='form_id',
        ),
        migrations.RenameField(
            model_name='grids',
            old_name='Qid',
            new_name='questionid',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Type',
            new_name='questionType',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Qid',
            new_name='questionid',
        ),
    ]
