# Generated by Django 3.2.13 on 2022-07-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('formcreater', '0015_auto_20220715_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='questionid',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='formresponses',
            old_name='questionid',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='formresponses',
            old_name='responseid',
            new_name='response_id',
        ),
        migrations.RenameField(
            model_name='grids',
            old_name='questionid',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='formid',
            new_name='form_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionid',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='formid',
            new_name='form_id',
        ),
        migrations.AlterField(
            model_name='forms',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
