# Generated by Django 3.2.13 on 2022-07-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formcreater', '0017_question_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choices',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='formresponses',
            name='response',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='grids',
            name='column',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='grids',
            name='row',
            field=models.CharField(max_length=30),
        ),
    ]
