# Generated by Django 3.2.13 on 2022-07-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formcreater', '0018_auto_20220718_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choices',
            field=models.CharField(default='null', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='formcreater.question'),
        ),
        migrations.AlterField(
            model_name='grids',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='formcreater.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='formcreater.forms'),
        ),
    ]
