# Generated by Django 3.2.13 on 2022-07-19 09:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('formcreater', '0021_auto_20220719_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response_id',
            new_name='responseid',
        ),
    ]
