# Generated by Django 3.2.13 on 2022-07-19 09:30

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('formcreater', '0022_rename_response_id_response_responseid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='responseid',
            new_name='response_id',
        ),
    ]
